[package]
name = "jc2_file_formats"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
jc2_hashing = { path = "../hashing" }

aligned-vec = { workspace = true }
bitflags = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
