[package]
name = "jc2_file_formats"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
jc2_hashing = { path = "../hashing" }

binrw = { workspace = true }
bitflags = { workspace = true }
num-traits = { workspace = true }
thiserror = { workspace = true }
