[package]
name = "jc2_hashing"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
const_for = "0.1"

binrw = { workspace = true }
paste = { workspace = true }
static_assertions = { workspace = true }
