[package]
name = "app"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
jc2_file_formats = { path = "../crates/file_formats" }

binrw = { workspace = true }
thiserror = { workspace = true }

bevy = { version = "0.13", default-features = false, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_gizmos",
    "bevy_pbr",
    "bevy_render",
    "bevy_text",
    "bevy_winit",
    "default_font",
    "multi-threaded",
    "tonemapping_luts",
    "webgpu",
    "x11",
    "dds",
    # development features
    "dynamic_linking",
    "embedded_watcher",
    "file_watcher",
] }
bevy_egui = { version = "0.27" }
bevy_file_dialog = { version = "0.5.0" }
bevy_panorbit_camera = { version = "0.18", features = ["bevy_egui"] }
